name: Upload AppStore

on:
  push:
    # branches: [ main, develop ]
    branches: [main]

jobs:
  uoload_app_store:
    runs-on: macos-latest
    steps:
      - name: Check-out my repository
        uses: actions/checkout@v2

      - name: Set up flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.22.2
          channel: 'stable'
          cache: true

      - name: Download Flutter packages
        run: flutter pub get

      # - name: Set github env variable for main branch
      #   run: |
      #     if [[ ${{ github.ref == 'refs/heads/main' }} ]]; then
      #       echo "IS_MAIN_BRANCH=true" >> $GITHUB_ENV
      #     else
      #       echo "IS_MAIN_BRANCH=false" >> $GITHUB_ENV
      #     fi

      - name: Import Provisioning Profile
        env:
          PROVISIONING_PROFILE: ${{ github.ref == 'refs/heads/main' && secrets.PROVISIONING_PROFILE || secrets.DEV_PROVISIONING_PROFILE }}
          MY_ENV_VAR: ${{ github.ref == 'refs/heads/main' && 'mainです' || 'その他です' }}
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo $MY_ENV_VAR
          profile_name="distribution_dev_sample_github_actions_2"
          echo "${{ github.ref }}"
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo 条件満たしている
            profile_name="distribution_sample_github_actions_2"
          fi
          echo $profile_name
          echo $PROVISIONING_PROFILE | base64 -d > ~/Library/MobileDevice/Provisioning\ Profiles/$profile_name.mobileprovision

      - name: Import Code-Signing Certificates
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.DISTRIBUTION_CERTIFICATE_P12 }}
          p12-password: ${{ secrets.DISTRIBUTION_CERTIFATE_P12_PASS }}

      - name: Create ipa file
        env:
          # secretsに保存したエンコード済みのjsonファイルをmainブランチかどうかで環境変数に保持する値を変更する
          DART_DEFINES_BASE64: ${{ github.ref }}
        run: |
          export_options_file="DevExportOptions.plist"
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            export_options_file="ExportOptions.plist"
          fi
          echo $export_options_file
          # エンコードしてあるjsonファイルをデコードして元に戻す。
          # 戻したjsonファイルをdart-defineに指定する。
          flutter build ipa --export-options-plist=ios/$export_options_file --dart-define-from-file=dart_defines/dev.json --build-number ${GITHUB_RUN_NUMBER}

      - name: Upload to AppStoreConnect
        env: 
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_PASS: ${{ secrets.APPLE_APP_PASS }}
        run: xcrun altool --upload-app -type ios -f build/ios/ipa/*.ipa -u "$APPLE_ID" -p "$APPLE_APP_PASS"
