name: Dev版をAppStoreConnectへのupload

on:
  push:
    branches: [ main ]

jobs:
  uoload_app_store_connect:
    name: Dev版をAppStoreConnectにUpload
    runs-on: macos-latest
    steps:
      - name: Checks-out my repository
        uses: actions/checkout@v2

      - name: Set up flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.22.2
          channel: 'stable'
          cache: true

      - name: Download Flutter packages
        run: flutter pub get

      - name: Import Provisioning Profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo -n ${{ secrets.DEV_PROVISIONING_PROFILE }} | base64 -d > ~/Library/MobileDevice/Provisioning\ Profiles/distribution_dev_sample_github_actions_2.mobileprovision

      - name: Import Code-Signing Certificates
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.DISTRIBUTION_CERTIFICATE_P12 }}
          p12-password: ${{ secrets.DISTRIBUTION_CERTIFATE_P12_PASS }}

      - name: Create ipa file
        run: |
          flutter build ipa --export-options-plist=ios/DevExportOptions.plist --build-number ${GITHUB_RUN_NUMBER}

      - name: Upload to AppStoreConnect
        env: 
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_PASS: ${{ secrets.APPLE_APP_PASS }}
        run: xcrun altool --upload-app -type ios -f build/ios/ipa/*.ipa -u "$APPLE_ID" -p "$APPLE_APP_PASS"
