name: Upload AppStore

on:
  push:
    branches: [ main, develop ]

jobs:
  uoload_app_store:
    runs-on: macos-latest
    steps:
      - name: Check-out my repository
        uses: actions/checkout@v2

      - name: Set up flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.22.2
          channel: 'stable'
          cache: true

      - name: Download Flutter packages
        run: flutter pub get

      # - name: Set github env variable for main branch
      #   run: |
      #     if [[ ${{ github.ref == 'refs/heads/main' }} ]]; then
      #       echo "is_main_branch=true" >> $GITHUB_ENV
      #     else
      #       echo "is_main_branch=false" >> $GITHUB_ENV
      #     fi

      - name: Import Provisioning Profile
        env:
          PROVISIONING_PROFILE: ${{ github.ref == 'refs/heads/main' && secrets.PROVISIONING_PROFILE || secrets.DEV_PROVISIONING_PROFILE }}
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          profile_name="dev sample github actions2"
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            profile_name="sample github actions2"
          fi
          echo $profile_name
          echo $PROVISIONING_PROFILE | base64 -d > ~/Library/MobileDevice/Provisioning\ Profiles/$profile_name.mobileprovision

      - name: Import Code-Signing Certificates
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.DISTRIBUTION_CERTIFICATE_P12 }}
          p12-password: ${{ secrets.DISTRIBUTION_CERTIFATE_P12_PASS }}

      - name: Create ipa file
        env:
          # secretsに保存したエンコード済みのjsonファイルをmainブランチかどうかで環境変数に保持する値を変更する
          DART_DEFINE_BASE64: ${{ github.ref == 'refs/heads/main' && secrets.DART_DEFINES_BASE64 || secrets.DEV_DART_DEFINES_BASE64}}
        run: |
          export_options_file="DevExportOptions.plist"
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            export_options_file="ExportOptions.plist"
          fi
          echo TargetExportOptionsFile: ${export_options_file}

          mkdir dart_defines
          dart_define_file_name=dev
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            dart_define_file_name=prod
          fi
          echo TargetDartDefinesFileName: ${dart_define_file_name}

          ls -la

          touch dart_defines/$dart_define_file_name.json

          cd dart_defines
          ls -la
          cd ../

          echo $DART_DEFINE_BASE64 | base64 -d > dart_defines/$dart_define_file_name.json
          flutter build ipa --export-options-plist=ios/$export_options_file --dart-define-from-file=dart_defines/$dart_define_file_name.json --build-number ${GITHUB_RUN_NUMBER}

      - name: Upload to AppStoreConnect
        env: 
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_PASS: ${{ secrets.APPLE_APP_PASS }}
        run: xcrun altool --upload-app -type ios -f build/ios/ipa/*.ipa -u "$APPLE_ID" -p "$APPLE_APP_PASS"
