name: ワークフロー手動実行テスト

on:
  push:
    branches: [main]
  workflow_dispatch: 
    inputs:
      name:
        description: 'Name'
        required: true

jobs:
  workflow-dispatch-test:
    runs-on: ubuntu-22.04

    steps:
      - name: print log
        run: echo Hello! ${{ github.event.inputs.name }}
